@Inventario.API_HostAddress = http://localhost:5104
@itemId = 267923a6-0450-4dff-a82c-d355eec979d3
@userId = user-123

GET {{Inventario.API_HostAddress}}/api/ItemInventario
Accept: application/json
X-User-Id: {{userId}}

###

GET {{Inventario.API_HostAddress}}/api/ItemInventario/{{itemId}}
Accept: application/json
X-User-Id: {{userId}}

###

POST {{Inventario.API_HostAddress}}/api/ItemInventario
Content-Type: application/json
X-User-Id: {{userId}}

{
  "nome": "Notebook Dell",
  "descricao": "Notebook de trabalho",
  "marca": "Dell",
  "modelo": "Latitude 5420",
  "valorCompra": 4500.00,
  "categoriaId": "a52b5010-40e4-4cd3-8017-ddf686b7ef9d",
  "localId": "94cd7b41-e0f1-4722-ade4-273500e316db",
  "dataAquisicao": "2026-04-01T00:00:00Z"
}

###

PUT {{Inventario.API_HostAddress}}/api/ItemInventario/{{itemId}}
Content-Type: application/json
X-User-Id: {{userId}}

{
  "nome": "Notebook Dell Atualizado",
  "descricao": "Notebook de trabalho atualizado",
  "marca": "Dell",
  "modelo": "Latitude 7200",
  "valorCompra": 4500.00,
  "categoriaId": "a52b5010-40e4-4cd3-8017-ddf686b7ef9d",
  "localId": "94cd7b41-e0f1-4722-ade4-273500e316db",
  "dataAquisicao": "2026-04-01T00:00:00Z"
}

###

DELETE {{Inventario.API_HostAddress}}/api/ItemInventario/{{itemId}}
Accept: application/json
X-User-Id: {{userId}}

###
